### ISSUE TITLE
MALT crash with exit 1 - not retred

### ISSUE THREAD

**Issue by jfy133** [jfy133/eager#26]
If MALT runs out of memory (heapspace), java crashes with exit 1.

Need to add to extra code (1) to error strategy

```
  --- LOADING ---:
  Reading file: /projects1/malt/databases/indexed/index040/full-nt_2017-10/ref.idx
  10% 20% 30% 40% 50% 60% 70% 80% 90% 100% (2.7s)
  Reading file: /projects1/malt/databases/indexed/index040/full-nt_2017-10/ref.db
  10% 20% 30% 40% 50% 60% 70% 80% 90% 100% (2191.7s)
  100% (0.0s)
  Number of sequences:    44,955,571
  Number of letters: 160,371,031,385
  LOADING table (0) ...
  Reading file: /projects1/malt/databases/indexed/index040/full-nt_2017-10/index0.idx
  Reference sequence type: DNA
  Index was built using stepSize=2
  100% (0.0s)
  Reading file: /projects1/malt/databases/indexed/index040/full-nt_2017-10/table0.idx
  10% 20% 30% 40% 50% 60% 70% 80% 90% 100% (76.1s)
  java.lang.OutOfMemoryError: Java heap space
  	at megan.io.IntFileGetterInMemory.<init>(IntFileGetterInMemory.java:51)
  	at malt.data.ReferencesHashTableAccess.<init>(ReferencesHashTableAccess.java:107)
  	at malt.MaltRun.run(MaltRun.java:290)
  	at malt.MaltRun.main(MaltRun.java:75)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
  	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
```

```
fellows@mpi-sdag1:/projects1/users/fellows/screening/191217_NS500559_0069_AHV3JLBGXC/output/work/03/b78196864bb9bb43e9a719dae21257$ cat .exitcode 
1
```

**Comment by jfy133** [comment]
Fixed in https://github.com/jfy133/eager/commit/e2468d4284881e529dae24cf188087d3a7669ed3

however SHH profile doesn't work because first time fail sees too much memory, so retry happens twice and CPU goes too high.

Need to allow only two condiitons on the type of memory requested 64
